apiVersion: apps/v1
kind: Deployment
metadata:
  name: castai-mem-limit-test
  labels:
    app: mem-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mem-test
  template:
    metadata:
      labels:
        app: mem-test
    spec:
      containers:
        - name: memory-container
          image: busybox
          command: ["sh", "-c", "sleep 3600"]
          resources:
            requests:
              memory: "50Mi"
              cpu: "80m"
            limits:
              memory: "200Mi"

